### ISSUE TITLE
Crypt.verify outputting diagnostic information

### ISSUE THREAD

**Issue by serotonincrash** [AlexXanderGrib/crypt-pass#1]
I've noticed that when I call `.verify()` it actually prints some diagnostic information such as the name of the adapter being used as well as the hash itself. 

![image](https://user-images.githubusercontent.com/33486837/187067819-14b35a28-d487-4237-8da5-4ed3278fcb2b.png)

Is this intended behaviour? I can't seem to find any sign that either my code or the `.verify()` implementations would output anything.

Apologies if this is a mistake on my end. 

Here's the function that calls `.verify()`:
```js
async function loginUser(username: string, password: string) {
    let user = await User.findOne({$or:[{username: username}, {email: username}]});

    if (user === null) {
        throw new Error("Login failed: user not found")
    }

    // Validate password

    let isPasswordCorrect = await crypt.verify(user.password, password);

    if (!isPasswordCorrect) {
        throw new Error("Login failed: incorrect password")
    }
    return user;
}
```

**Comment by AlexXanderGrib** [comment]
Fixed in 1.2.0. Thanks for waiting
